### ISSUE TITLE
IndexError: list index out of range when porting pass to resholve

### ISSUE THREAD

**Issue by cole-h** [abathur/resholve#32]
I've gisted the Nix log and diff I used here: https://gist.github.com/cole-h/6f0eee3ac18180a8275deb288c4651d1. (The diff was applied against https://github.com/abathur/nixpkgs/tree/resholve-0.6.0-rc.1.)

**Comment by abathur** [comment]
This is falling over on this bit in pass:

```bash
find "$SECURE_TMPDIR" -type f -exec $SHRED {} +`
```

The reason is a little complicated, and the fix is too (though it may push me to do something I've been trying to avoid...).

In the interim, you _might_ be able to partially-unblock by adding a fix directive for `"$SHRED" = [ "shred" ];`. 

This should _actually_ use `shred -f -z`, but that also shook loose a problem with the suitability of the new variable-fixing syntax, which in retrospect is a bit myopic in directly targeting single words. I naively thought we wouldn't run into many of these--shellcheck and most bash/shell tutorials and style guides are very militant about double-quoting parameter expansions, and a "quoted space-separated word" isn't a valid command (unless there's an executable named `quoted\ space-separated\ word`). But, alas, here's one that counts on expansion. :)

I'll update when there's a more-proper fix.

**Comment by abathur** [comment]
This is roughly fixed with the 0.6.0 release, though you'll still need an inner quote or to escape the spaces.

If it's common enough to become a real issue for someone they can presumably help update the Nix API to escape them by default. :)

**Comment by abathur** [comment]
As of the 0.8.0 release (which isn't available in any channels yet) the Nix API ~should auto-quote/escape these.
