### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by dotlambda** [abathur/resholve#88]
Python 2 has been EOL since January 1, 2020 and it is insecure. That's relevant when parsing other people's code. See https://github.com/NixOS/nixpkgs/pull/201859.

**Comment by abathur** [comment]
- @dotlambda py3 is a no-go because oil is in 27
- @figsoda I'm not quite sure what you mean by opy, but if you mean the python bytecode compiler inside of the oil repo... I don't think this is a good idea. This code is pretty old. It might be under-test and therefore working, but there've been notes in Oil for a while that it was basically a dead-end experiment that will eventually be completely replaced with the mycpp work they've been doing (leaving resholve stuck at that version of Oil). Going down this route entails building the vendored python27 inside the oil repo; I gave this a try on macOS and it fails on:
    ```
    /private/tmp/nix-build-python2.7-oildev-unstable-2021-07-14.drv-0/source/Python-2.7.13/configure: line 8397: gcc: command not found
    /private/tmp/nix-build-python2.7-oildev-unstable-2021-07-14.drv-0/source/Python-2.7.13/configure: line 8398: test: <: unary operator expected
    /private/tmp/nix-build-python2.7-oildev-unstable-2021-07-14.drv-0/source/Python-2.7.13/configure: line 8444: /usr/bin/arch: Operation not permitted
    configure: error: Unexpected output of 'arch' on OSX
    ```
- @7c6f434c After wasting a couple hours clearing hurdles I ran into an error that reminded me that I *have* tried this before, but the issue is that Oil leans on multiple C extensions

**Comment by 7c6f434c** [comment]
Ohhh OK I was too naively reading the claim that OPy is a small _subset_ of Python2… Sorry.

**Comment by abathur** [comment]
I won't pretend to have a really deep understanding of it. IIUC it's a subset in that it builds the py27 and then uses some tree-shaking process to try and track what parts of that python are actually exercised by the oil codebase, and then do (magic? crimes?) to get discard parts that it didn't need for whatever load/memory performance it can claw back by doing so.

**Comment by SamLukeYes** [comment]
Can [xonsh](https://xon.sh/) be used to replace oil?

**Comment by figsoda** [comment]
xonsh's syntax is probably too incompatible with bash to be useful here

**Comment by abathur** [comment]
My understanding aligns with figsoda's. xonsh is Python + some bits of Shell. As they put it on the landing page:
> The language is a superset of Python 3.6+ with additional shell primitives that you are used to from Bash and IPython.

Pretty trivial to find valid bash that it can't parse:

```console
$ xonsh <<EOF
{ declare -gA bashup_ev bashup_ev_r
} 
EOF

  File "<stdin>", line 1
    { declare -gA bashup_ev bashup_ev_r
                 ^
SyntaxError: ('code: bashup_ev',)
```

Oil's OSH parser is almost-entirely-Bash-compatible.

**Comment by SamLukeYes** [comment]
Well, I see some discussions about xonsh's bash-compatibility in https://github.com/xonsh/xonsh/issues/4015, and the issue author has mentioned [bashlex - Python parser for bash](https://github.com/idank/bashlex). Would it be helpful here?

**Comment by abathur** [comment]
resholve uses the OSH parser (and, thus, python2) because it *forms the foundation of a working shell that can actually execute nearly all of Bash and is tested against a massive corpus of wild scripts*, which is generally what we want for a tool that we can trust to be able to parse, rewrite, and emit the vast majority of Bash/POSIX shell found in the wild without breaking it.

bashlex (or any other bash parser) *might* work, but it isn't battle-tested like OSH is. It exists to power explainshell.com, which generally just needs to handle a single line of shell at a time. It doesn't have to worry about deploying broken scripts if the parser doesn't recognize a structure and subtly changes it on the way back out. If you look through the issues, it's common to see syntax that doesn't work and the maintainer acknowledges that it doesn't work because he didn't need it for his case.

**Comment by georgyo** [comment]
~3 years later, are there still no plans to upgrade to python3?
OSH states that their project is "OBSOLETE"
Has the maturity of other bash parser improved enough to consider using an alternative?

 Python2 was EOL 6 years ago. Is this project nearing EOL?

**Comment by abathur** [comment]
> ~3 years later, are there still no plans to upgrade to python3?

There were always plans, but this isn't a trivial 2->3 "port" that I'm just too dumb to execute. 

Looking into whether the path forward has cleared up on Oils' end is on my mood board for 2026. (edit: last year's edition: https://github.com/abathur/resholve/issues/112#issuecomment-2744603725)

> OSH states that their project is "OBSOLETE"

What are you talking about?

**Comment by georgyo** [comment]
> There were always plans, 

This ticket and #112 are both closed as not planned, hence my confusion. Though I did not read all of #112 as the first comment is a pointer to this ticket. 

> but this isn't a trivial 2->3 "port" that I'm just too dumb to execute.

At no point did I claim that, or even allude to that. The question was if there was motivation and a plan. There being a plan is good news!

>> OSH states that their project is "OBSOLETE"

> What are you talking about?

This was my fault, googling `osh python` and `osh shell` both return this python2 project: https://github.com/geophile/osh, which was my confusion.

**Comment by abathur** [comment]
Damned if I do and damned if I don't :)

We have very well-worn expectations of what "port to python3" means for a python2 codebase. Those expectations don't really apply here.

If I leave these open while I wait for it to ripen, people see a years-old "port to python3" issue as:
- a sign this is abandonware whose maintainer doesn't care to do the typically-straightforward work it implies
- an invitation go try to do this straightforward work themselves (which, unless they understand the situation deeply, is almost certainly going to waste their time and be more than they intended to bite off)

I close the issues to stave these off, but it obviously leaves room for people to get confused and either open a new one or assume it means there's no interest in doing the work to break the python2 dependency when it's ripe.

**Comment by Sigmanificient** [comment]
@abathur `resholve` is the only leftover piece that uses python2 in nixpkgs, see this tracking issue:
- https://github.com/NixOS/nixpkgs/issues/479927
